version: "3.0"
services:
  db:
    container_name: "task_1"
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data/
    ports:
      - "5436:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge
volumes:
  dbdata: